image: registry.gitlab.com/role_unit/role_unit_containers:build

variables:
  DOCKER_DRIVER: overlay2
  STORAGE_DRIVER: vfs
  DEBIAN_FRONTEND: noninteractive

services:
- docker:dind

stages:
  - images
  - library
  - role-init

before_script:
  - chmod o-w tests

.distribution_testing:
  script:
    - RU_ENV_IMAGE=${CI_JOB_NAME} tests/bash_unit tests/tests_role_unit
  stage: images

debian11:
  extends: .distribution_testing

debian10:
  extends: .distribution_testing

centos8:
  extends: .distribution_testing

centos7:
  extends: .distribution_testing

archlinux:
  extends: .distribution_testing

inventory:
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_inventory
  stage: library

requirements:
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_requirements
  stage: library

docker:
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_docker
  stage: library

podman:
  script:
    - echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - apk update
    - apk add podman
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_podman
  stage: library

podman-compose:
  script:
    - echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - apk update
    - apk add podman
    - pip3 install podman-compose
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_podman-compose
  stage: library

multiplicity:
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_double
  stage: library

groups:
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_groups
  stage: library

simultaneity:
  script:
    - tests/bash_unit tests/tests_run_the_same_twice
  stage: library

role_init:
  script:
    - tests/bash_unit tests/tests_role_init
  stage: role-init
