image: registry.gitlab.com/role_unit/role_unit_containers:build

variables:
  DOCKER_DRIVER: overlay2
  STORAGE_DRIVER: vfs
  DEBIAN_FRONTEND: noninteractive

services:
- docker:dind

stages:
  - images
  - library
  - role-init

before_script:
  - chmod o-w tests

.all:
  tags:
  - role-unit

.distribution_testing:
  extends: .all
  script:
    - RU_ENV_IMAGE=${CI_JOB_NAME} tests/bash_unit tests/tests_role_unit
  stage: images

debian11:
  extends: .distribution_testing

debian10:
  extends: .distribution_testing

centos8:
  extends: .distribution_testing

#centos7:
#  extends: .distribution_testing

archlinux:
  extends: .distribution_testing

ubuntu2204:
  extends: .distribution_testing

ubuntu2004:
  extends: .distribution_testing

inventory:
  extends: .all
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_inventory
  stage: library

requirements:
  extends: .all
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_requirements
  stage: library

docker:
  extends: .all
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_docker
  stage: library

#podman:
#  extends: .all
#  script:
#    - echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
#    - apk update
#    - apk add podman
#    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_podman
#  stage: library

#podman-compose:
#  extends: .all
#  script:
#    - echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
#    - apk update
#    - apk add podman jq
#    - pip3 install podman-compose
#    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_podman-compose
#  stage: library

multiplicity:
  extends: .all
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_double
  stage: library

groups:
  extends: .all
  script:
    - RU_ENV_IMAGE=debian11 tests/bash_unit tests/tests_role_unit_groups
  stage: library

simultaneity:
  extends: .all
  script:
    - tests/bash_unit tests/tests_run_the_same_twice
  stage: library

role_init:
  extends: .all
  script:
    - tests/bash_unit tests/tests_role_init
  stage: role-init
