image: registry.gitlab.com/role_unit/role_unit_containers:build

variables:
  DOCKER_DRIVER: overlay2
  DEBIAN_FRONTEND: noninteractive

services:
- docker:dind

stages:
  - images
  - library
  - role-init

before_script:
  - chmod o-w tests

.distribution_testing:
  script:
    - RU_ENV_IMAGE=${CI_JOB_NAME} tests/bash_unit tests/tests_role_unit
  stage: images

debian10:
  extends: .distribution_testing

debian9:
  extends: .distribution_testing

debian8:
  extends: .distribution_testing

centos8:
  extends: .distribution_testing

centos7:
  extends: .distribution_testing

centos6:
  extends: .distribution_testing

archlinux:
  extends: .distribution_testing

requirements:
  script:
    - RU_ENV_IMAGE=debian9 tests/bash_unit tests/tests_role_unit_requirements
  stage: library

docker:
  script:
    - RU_ENV_IMAGE=debian9 tests/bash_unit tests/tests_role_unit_docker
  stage: library

multiplicity:
  script:
    - RU_ENV_IMAGE=debian9 tests/bash_unit tests/tests_role_unit_double
  stage: library

simultaneity:
  script:
    - tests/bash_unit tests/tests_run_the_same_twice
  stage: library

role_init:
  script:
    - tests/bash_unit tests/tests_role_init
  stage: role-init
