---
language: python
python: "2.7"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version

script:
  - export PATH=$PATH:.
  - RU_ENV_IMAGE=debian7 tests/bash_unit tests/tests_role_unit
  - RU_ENV_IMAGE=debian8 tests/bash_unit tests/tests_role_unit
  - RU_ENV_IMAGE=debian9 tests/bash_unit tests/tests_role_unit
  - RU_ENV_IMAGE=centos6 tests/bash_unit tests/tests_role_unit
  - RU_ENV_IMAGE=centos7 tests/bash_unit tests/tests_role_unit
  - RU_ENV_IMAGE=debian9 tests/bash_unit tests/tests_role_unit_double
