---
language: python
python: "2.7"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version
  - ansible -i localhost, -c local all -m setup
  - docker pull multimediabs/plumb_unit:centos6
  - docker pull multimediabs/plumb_unit:centos7
  - docker pull multimediabs/plumb_unit:debian_jessie
  - docker pull multimediabs/plumb_unit:debian_wheezy
  - docker pull multimediabs/plumb_unit:debian_stretch
  - docker pull multimediabs/plumb_unit:archlinux

script:
  - export PATH=$PATH:.
  - tests/bash_unit tests/tests_role_unit
  - tests/bash_unit tests/tests_role_unit_debian8
