image:https://gitlab.com/role_unit/role_unit/badges/master/pipeline.svg[link="https://gitlab.com/role_unit/role_unit/commits/master",title="pipeline status"]

= role_unit

The goal of this project is to test your ansible system automation. Its goal is basically to test ansible roles, but role_unit's own tests are an example of an other usage that can be made.

Role_unit is based on https://github.com/pgrange/bash_unit[bash_unit], a bash unit-testing framework. The first provides the second a controlled environment for reproductible testing over multiple environments.

== prerequisites

* docker
* ansible

== usage

To create a new role tested with role_unit, place yourself in the directory where you want the role and run role_init:

----
cd /my/ansible/dir/roles
/path/to/role_init my_role
----

This will create an empty role with the testing tools in the tests directory. A default tests file is created. To run the tests, you will have to specify the distribution by setting the RU_ENV_IMAGE variable (see below).

The tests directory is a standard ansible structure : if you place a group_vars directory it will be used.

You have a list of functions you can call in your test file, described below.

=== ru_init

Initiates testing environment, i.e. creates containers or virtual machines depending on configuration.

=== ru_ansible_init

Initiates ansible inventory and playbook necessary to test your ansible role.

=== ru_run_ansible

Actually run ansible-playbook on your testing environment.

=== ru_run [ -d ] [ -n N ] cmd ...

Runs the specified command on all of the servers or just on the one specified. N is the number of the server you want to run the command on.

If you specify -d option, this will launch command in a detached mode. There may be evolution in the future about that but for now those options must be sepcified in this order only.

=== ru_ansible_fact [ -n N ] fact_name...

Returns the specified ansible fact for all of the servers or just on the one specified. N is the number of the server you want to get the fact from.

== parameters

there is only one mandatory environment variable, which is RU_ENV_IMAGE. It defines the linux flavor you will run your tests against. Default configuration pulls docker images from role_unit containers repository (registry.gitlab.com/role_unit/role_unit_containers). Actually, you can choose among :

* debian 9 (stretch)
* debian 8 (jessie)
* centos 7
* centos 6

role_unit behaviour can be changed using environment variables:

* RU_ENV_NAME defines the testing environment name. It is the name of the role you will test.
* RU_ENV_DOCKER_REPO defines the docker repository to pull images from.
* RU_ENV_IMAGE defines the system image used to create test environment.
* RU_COUNT sets the number of containers or virtual machines
* RU_DEBUG when set to 1, will make role_unit not to stop containers after the run, so you can enter them to check things.

== about namespace

Role unit functions are prefixed by ru_. Role_unit environment variables for configuration are prefixed by RU_. Internal variables are prefixed with ru_. We keep it that way to minimize impact on tested environment.

== tests

=== prerequisites

Role_unit is tested with role_unit, so preprequisites are the same.

=== run

The tests are described in the .gitlab-ci.yml file.

To run the tests, you will have to launch the commands in the "script" part of the .gitlab-ci.yml file.
