#!/usr/bin/env bash

# Functions
usage() {
  my_name=$(basename $0)
  [ $# -gt 0 ] && echo "$@" >&2
  echo "usage : ${my_name} [ -v|--verbose ] [ -h|--help ] ROLE_NAME ...
  creates a ROLE_NAME directory in the current directory, with a dummy role and unit tests embeded.
  if multiple role names are specified a role directory will be created for each.
  -v|--verbose : activates verbose mode
     -h|--help : displays this help" >&2
  exit 1
}

create_an_ansible_role() {
  local role_name=$1
  # Create empty role
  mkdir ${verbose_flag} -p ${role_name}/{tasks,meta}
  [ ! -f ${role_name}/tasks/main.yml ] && cp ${verbose_flag} ${role_unit_dir}/role_files/tasks ${role_name}/tasks/main.yml
  # Dependencies to make role usable by ansible-galaxy
  [ ! -f ${role_name}/meta/main.yml ] && cp ${verbose_flag} ${role_unit_dir}/role_files/meta ${role_name}/meta/main.yml
}

make_directory_testable() {
  local role_name=$1
  # Testing environment
  mkdir ${verbose_flag} -p ${role_name}/tests
  cp ${verbose_flag} ${role_unit_dir}/tools/bash_unit ${role_name}/tests
  cp ${verbose_flag} -r ${role_unit_dir}/lib ${role_name}/tests
  [ ! -f ${role_name}/tests/ansible.cfg ] && cp ${verbose_flag} ${role_unit_dir}/tools/ansible.cfg ${role_name}/tests
  [ ! -f ${role_name}/tests/tests_${role_name} ] && cp ${verbose_flag} ${role_unit_dir}/tools/tests ${role_name}/tests/tests_${role_name}
}

# Check parameters
getopt -o vh --long verbose,help -n 'option parsing' -- "$@" > /dev/null
[ $? != 0 ] && usage "Failed parsing options."

verbose_mode=false
verbose_flag=

while true; do
  case "$1" in
    -v | --verbose )
      verbose_mode=true
      verbose_flag="-v"
      shift
      ;;
    -h | --help )
      usage
      ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

[ $# -lt 1 ] && usage "role name is mandatory"

# Set readlink option. -e is not available on all systems
readlink_opt="-e"
readlink ${readlink_opt} / >/dev/null 2>&1 || readlink_opt="-f"

# determine where we create dir and where script really is
role_dir=$(pwd)
role_unit_dir=$(dirname $(readlink ${readlink_opt} $0))

while [ $# -ge 1 ]
do
  create_an_ansible_role $1
  make_directory_testable $1
  shift
done
